# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coffefi.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='coffefi.proto',
  package='coffefi',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rcoffefi.proto\x12\x07\x63offefi\"\x07\n\x05\x45mpty\"\"\n\x0bTemperature\x12\x13\n\x0btemperature\x18\x01 \x01(\x05\"\x18\n\x06Status\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x18\n\x06Switch\x12\x0e\n\x06switch\x18\x01 \x01(\x08\"\x16\n\x05Power\x12\r\n\x05power\x18\x01 \x01(\t2\xa4\x01\n\x07\x43offeFi\x12;\n\x11TemperatureSensor\x12\x0e.coffefi.Empty\x1a\x14.coffefi.Temperature\"\x00\x12)\n\x04Lamp\x12\x0f.coffefi.Switch\x1a\x0e.coffefi.Power\"\x00\x12\x31\n\x0c\x43offeMachine\x12\x0e.coffefi.Empty\x1a\x0f.coffefi.Status\"\x00\x62\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='coffefi.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=33,
)


_TEMPERATURE = _descriptor.Descriptor(
  name='Temperature',
  full_name='coffefi.Temperature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='temperature', full_name='coffefi.Temperature.temperature', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=69,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='coffefi.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='coffefi.Status.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=95,
)


_SWITCH = _descriptor.Descriptor(
  name='Switch',
  full_name='coffefi.Switch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='switch', full_name='coffefi.Switch.switch', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=121,
)


_POWER = _descriptor.Descriptor(
  name='Power',
  full_name='coffefi.Power',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='power', full_name='coffefi.Power.power', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=145,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Temperature'] = _TEMPERATURE
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['Switch'] = _SWITCH
DESCRIPTOR.message_types_by_name['Power'] = _POWER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'coffefi_pb2'
  # @@protoc_insertion_point(class_scope:coffefi.Empty)
  })
_sym_db.RegisterMessage(Empty)

Temperature = _reflection.GeneratedProtocolMessageType('Temperature', (_message.Message,), {
  'DESCRIPTOR' : _TEMPERATURE,
  '__module__' : 'coffefi_pb2'
  # @@protoc_insertion_point(class_scope:coffefi.Temperature)
  })
_sym_db.RegisterMessage(Temperature)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'coffefi_pb2'
  # @@protoc_insertion_point(class_scope:coffefi.Status)
  })
_sym_db.RegisterMessage(Status)

Switch = _reflection.GeneratedProtocolMessageType('Switch', (_message.Message,), {
  'DESCRIPTOR' : _SWITCH,
  '__module__' : 'coffefi_pb2'
  # @@protoc_insertion_point(class_scope:coffefi.Switch)
  })
_sym_db.RegisterMessage(Switch)

Power = _reflection.GeneratedProtocolMessageType('Power', (_message.Message,), {
  'DESCRIPTOR' : _POWER,
  '__module__' : 'coffefi_pb2'
  # @@protoc_insertion_point(class_scope:coffefi.Power)
  })
_sym_db.RegisterMessage(Power)



_COFFEFI = _descriptor.ServiceDescriptor(
  name='CoffeFi',
  full_name='coffefi.CoffeFi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=148,
  serialized_end=312,
  methods=[
  _descriptor.MethodDescriptor(
    name='TemperatureSensor',
    full_name='coffefi.CoffeFi.TemperatureSensor',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_TEMPERATURE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Lamp',
    full_name='coffefi.CoffeFi.Lamp',
    index=1,
    containing_service=None,
    input_type=_SWITCH,
    output_type=_POWER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CoffeMachine',
    full_name='coffefi.CoffeFi.CoffeMachine',
    index=2,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_STATUS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COFFEFI)

DESCRIPTOR.services_by_name['CoffeFi'] = _COFFEFI

# @@protoc_insertion_point(module_scope)
